//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RGiesecke.DllExport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RGiesecke.DllExport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exporting as {1} and index {0}.
        /// </summary>
        internal static string AddingVtEntry_0_export_1_ {
            get {
                return ResourceManager.GetString("AddingVtEntry_0_export_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous export name &apos;{0}&apos; on &apos;{1}&apos;.&apos;{2}&apos;..
        /// </summary>
        internal static string Ambiguous_export_name_0_on_1_2_ {
            get {
                return ResourceManager.GetString("Ambiguous_export_name_0_on_1_2_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while calling {0}: {1}.
        /// </summary>
        internal static string An_error_occurred_while_calling_0_1_ {
            get {
                return ResourceManager.GetString("An_error_occurred_while_calling_0_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (alias {0}).
        /// </summary>
        internal static string AssemblyAlias {
            get {
                return ResourceManager.GetString("AssemblyAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calling &apos;{0}&apos; with {1}.
        /// </summary>
        internal static string calling_0_with_1_ {
            get {
                return ResourceManager.GetString("calling_0_with_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &apos;After&apos;.
        /// </summary>
        internal static string CopyAfterContextName {
            get {
                return ResourceManager.GetString("CopyAfterContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy &apos;Before&apos;.
        /// </summary>
        internal static string CopyBeforeContextName {
            get {
                return ResourceManager.GetString("CopyBeforeContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateTempDirectory.
        /// </summary>
        internal static string CreateTempDirectoryContextName {
            get {
                return ResourceManager.GetString("CreateTempDirectoryContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Notifier Context is &apos;{0}&apos;, it should have been &apos;{1}&apos;..
        /// </summary>
        internal static string Current_Notifier_Context_is___0____it_should_have_been___1___ {
            get {
                return ResourceManager.GetString("Current_Notifier_Context_is___0____it_should_have_been___1___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting unused reference to {0}{1}..
        /// </summary>
        internal static string Deleting_reference_to_0_ {
            get {
                return ResourceManager.GetString("Deleting_reference_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory &apos;{0}&apos; does not exist.
        /// </summary>
        internal static string Directory_0_does_not_exist {
            get {
                return ResourceManager.GetString("Directory_0_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate {0} specified..
        /// </summary>
        internal static string Duplicate_0_specified_ {
            get {
                return ResourceManager.GetString("Duplicate_0_specified_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export name &apos;{0}&apos; on &apos;{1}&apos;.&apos;{2}&apos; is Unicode, windows export names have to be basic latin and cannot contain quotes..
        /// </summary>
        internal static string Export_name_0_on_1__2_is_Unicode_windows_export_names_have_to_be_basic_latin {
            get {
                return ResourceManager.GetString("Export_name_0_on_1__2_is_Unicode_windows_export_names_have_to_be_basic_latin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtractExports.
        /// </summary>
        internal static string ExtractExportsContextName {
            get {
                return ResourceManager.GetString("ExtractExportsContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FindDuplicateExportMethods.
        /// </summary>
        internal static string FindDuplicateExportMethodsContextName {
            get {
                return ResourceManager.GetString("FindDuplicateExportMethodsContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found method: {0}.{1}.
        /// </summary>
        internal static string Found_method_0_1_ {
            get {
                return ResourceManager.GetString("Found_method_0_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input assembly does not exist..
        /// </summary>
        internal static string Input_assembly_does_not_exist {
            get {
                return ResourceManager.GetString("Input_assembly_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file must be a DLL..
        /// </summary>
        internal static string Input_file_must_be_a_DLL {
            get {
                return ResourceManager.GetString("Input_file_must_be_a_DLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file required..
        /// </summary>
        internal static string Input_file_required {
            get {
                return ResourceManager.GetString("Input_file_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new declaration: {0}.
        /// </summary>
        internal static string NewDeclaration_0_ {
            get {
                return ResourceManager.GetString("NewDeclaration_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No action for parser state {0}.
        /// </summary>
        internal static string No_action_for_parser_state_0_ {
            get {
                return ResourceManager.GetString("No_action_for_parser_state_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no declaration....
        /// </summary>
        internal static string no_declaration___ {
            get {
                return ResourceManager.GetString("no_declaration___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to no name....
        /// </summary>
        internal static string no_name___ {
            get {
                return ResourceManager.GetString("no_name___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No paramaters provided, at least the input assembly name is needed..
        /// </summary>
        internal static string No_paramaters_provided__at_least_the_input_assembly_name_is_needed {
            get {
                return ResourceManager.GetString("No_paramaters_provided__at_least_the_input_assembly_name_is_needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to old declaration: {0}.
        /// </summary>
        internal static string OldDeclaration_0_ {
            get {
                return ResourceManager.GetString("OldDeclaration_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse IL.
        /// </summary>
        internal static string ParseILContextName {
            get {
                return ResourceManager.GetString("ParseILContextName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing {0} lines of IL took {1} ms..
        /// </summary>
        internal static string Parsing_0_lines_of_IL_took_1_ms_ {
            get {
                return ResourceManager.GetString("Parsing_0_lines_of_IL_took_1_ms_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsing action &apos;{0}&apos; took {1} ms..
        /// </summary>
        internal static string Parsing_action_0_took_1_ms {
            get {
                return ResourceManager.GetString("Parsing_action_0_took_1_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform is {0}, creating binaries for each CPU platform in a separate subfolder....
        /// </summary>
        internal static string Platform_is_0_creating_binaries_for_each_CPU_platform_in_a_separate_subfolder {
            get {
                return ResourceManager.GetString("Platform_is_0_creating_binaries_for_each_CPU_platform_in_a_separate_subfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided key file &apos;{0}&apos; cannot be found..
        /// </summary>
        internal static string Provided_key_file_0_cannot_be_found {
            get {
                return ResourceManager.GetString("Provided_key_file_0_cannot_be_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &apos;{1}&apos; returned gracefully..
        /// </summary>
        internal static string R_0_1_returned_gracefully {
            get {
                return ResourceManager.GetString("R_0_1_returned_gracefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not return after {1} ms..
        /// </summary>
        internal static string R_0_did_not_return_after_1_ms {
            get {
                return ResourceManager.GetString("R_0_did_not_return_after_1_ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} did not return after {1} ms and it could not be stopped.
        ///{2}.
        /// </summary>
        internal static string R_0_did_not_return_after_1_ms_and_it_could_not_be_stopped {
            get {
                return ResourceManager.GetString("R_0_did_not_return_after_1_ms_and_it_could_not_be_stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing {0} from {1}.
        /// </summary>
        internal static string Removing_0_from_1_ {
            get {
                return ResourceManager.GetString("Removing_0_from_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination directory already exists..
        /// </summary>
        internal static string The_destination_directory_already_exists_ {
            get {
                return ResourceManager.GetString("The_destination_directory_already_exists_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{1}&apos;.&apos;{2}&apos; (export name &apos;{0}&apos;) is generic. Generic methods cannot be exported..
        /// </summary>
        internal static string The_method_1_2_is_generic_export_name_0_Generic_methods_cannot_be_exported_ {
            get {
                return ResourceManager.GetString("The_method_1_2_is_generic_export_name_0_Generic_methods_cannot_be_exported_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The method &apos;{1}&apos;.&apos;{2}&apos; (export name &apos;{0}&apos;) is not static. Only static methods can be exported..
        /// </summary>
        internal static string The_method_1_2_is_not_static_export_name_0_ {
            get {
                return ResourceManager.GetString("The_method_1_2_is_not_static_export_name_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type &apos;{1}&apos; cannot export the method &apos;{2}&apos; as &apos;{0}&apos; because it is generic or is nested within a generic type..
        /// </summary>
        internal static string The_type_1_cannot_export_the_method_2_as_0_because_it_is_generic_or_is_nested_within_a_generic_type {
            get {
                return ResourceManager.GetString("The_type_1_cannot_export_the_method_2_as_0_because_it_is_generic_or_is_nested_wit" +
                        "hin_a_generic_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown cpu platform &apos;{0}&apos;..
        /// </summary>
        internal static string Unknown_cpu_platform_0_ {
            get {
                return ResourceManager.GetString("Unknown_cpu_platform_0_", resourceCulture);
            }
        }
    }
}
