// This code was generated by a vsSolutionBuildEvent. 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
namespace net.r_eg.DllExport.Configurator
{
    using System;

    internal struct ConfVersion
    {
        public static readonly Version number = new Version(S_NUM_REV);

        public const string S_NUM = "1.5.2";
        public const string S_REV = "40158";

        public const string S_NUM_REV   = S_NUM + "." + S_REV;
        public const string BRANCH_SHA1 = "932cd0d";

        internal const string S_INFO = S_NUM_REV + " [ " + BRANCH_SHA1 + " ]";
    }
}